version: 0.2
batch:
  build-list:
    - identifier: build1
      env:
        compute-type: BUILD_GENERAL1_SMALL
      buildspec: build1.yml
    - identifier: build2
      env:
        compute-type: BUILD_GENERAL1_MEDIUM
      buildspec: build2.yml
      depend-on:
        - build1
phases:
  build:
    commands:
      - mkdir combine_artifacts_codebuild
      - echo 'file' > output_file
      - mv output_file combine_artifacts_codebuild
